name: Publish to Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
       
      - name: Publish to Maven Central
        run: ./gradlew clean publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername      : ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword      : ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId      : ${{ secrets.SIGNING_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PW }}
          ORG_GRADLE_PROJECT_signingInMemoryKey        : ${{ secrets.SIGNING_KEY }}
